version: '3.7'

services:
  idp.dev.local:
    build: build
    volumes:
      - ./simplesamlphp:/code
      - ./idp:/conf
    working_dir: /code
    environment:
      - SIMPLESAMLPHP_CONFIG_DIR=/conf/
    links:
      - mysql

  sp.dev.local:
    build: build
    volumes:
      - ./simplesamlphp:/code
      - ./sp:/conf
    working_dir: /code
    environment:
      - SIMPLESAMLPHP_CONFIG_DIR=/conf/
    command: apache2 -D FOREGROUND
    links:
      - memcached

  memcached:
    image: memcached

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sessions
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootpassword

  nginx:
    image: nginx:stable
    links:
      - idp.dev.local
      - sp.dev.local
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - '8080:80'
      - '8081:81'
